name: Revisor Diario de la CNBV

on:
  # Disparador programado (sin cambios)
  schedule:
    - cron: '0 12 * * *'
  
  # Disparador manual con una nueva opción
  workflow_dispatch:
    inputs:
      send_test_email:
        description: '✅ Marcar para enviar un correo de prueba ahora'
        required: true
        type: boolean
        default: false

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      # --- PASOS DE CONFIGURACIÓN (SIN CAMBIOS) ---
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      # --- EJECUCIÓN DEL SCRIPT (SIN CAMBIOS) ---
      - name: Run CNBV checker script
        run: python check_cnbv.py

      # --- LÓGICA DE NOTIFICACIÓN (MEJORADA) ---

      # 1. Revisa si el script encontró cambios
      - name: Check for file changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain last_headline.txt) ]]; then
            echo "File changed, proceeding to notification."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      # 2. Lee el nuevo titular y enlace si hubo cambios
      - name: Read new headline and link
        id: read_file
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          headline=$(head -n 1 last_headline.txt)
          link=$(tail -n 1 last_headline.txt)
          echo "headline=${headline}" >> $GITHUB_OUTPUT
          echo "link=${link}" >> $GITHUB_OUTPUT

      # 3. Envía un correo de ACTUALIZACIÓN si hubo cambios
      - name: Send Update Email Notification
        if: steps.check_changes.outputs.changed == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "🚨 Nueva Actualización de la CNBV Detectada"
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions Bot <${{ secrets.MAIL_USERNAME }}>
          body: |
            ¡Hola!
            Se ha detectado una nueva actualización en la sección de prensa de la CNBV.

            **Titular:** ${{ steps.read_file.outputs.headline }}

            **Puedes leerla aquí:** ${{ steps.read_file.outputs.link }}

            Este es un mensaje automático.

      # 4. Envía un correo de PRUEBA si se activó manualmente
      - name: Send Test Email Notification
        if: github.event.inputs.send_test_email == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "✅ Correo de Prueba - Sistema de Notificación CNBV"
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions Bot <${{ secrets.MAIL_USERNAME }}>
          body: |
            ¡Hola!

            Este es un correo de prueba para confirmar que el sistema de notificaciones por correo está funcionando correctamente.

            Tus credenciales y la configuración son correctas. El bot está listo para vigilar la página de la CNBV por ti.

            Saludos,
            GitHub Actions Bot

      # 5. Guarda los cambios en el repositorio si hubo una actualización real
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_headline.txt
          git commit -m "📝 Actualiza último titular de la CNBV"
          git push
